### ISSUE TITLE
Method for Quantization

### ISSUE THREAD

**Issue by YUJIE47** [martinbenes1996/jpeglib#21]
In your project which method should be used in the quantization process to convert floating-point numbers to integers: truncation (trunc) or rounding (round)? Thanks!!

**Comment by martinbenes1996** [comment]
**TLDR;** truncation

Not really though. jpeglib uses the libjpeg under the hood.
libjpeg performs DCT transform in fixed-point, followed by truncation (at least in 6b).
https://github.com/martinbenes1996/jpeglib/blob/master/src/jpeglib/cjpeglib/6b/jdct.h

There are two BUTs:
- the truncation may be applied several times, because precision may differ for different steps in the compression.
- Furthermore, what applies to one libjpeg/turbo/moz version may not apply to others, because there are differences between the versions. https://dl.acm.org/doi/pdf/10.1145/3531536.3532962
